language: android

jdk:
  - oraclejdk7

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - android-23
    - build-tools-23.0.3
    - extra-android-m2repository

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
